version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reportdb
    environment:
      POSTGRES_USER: reportuser
      POSTGRES_PASSWORD: reportpass
      POSTGRES_DB: reportdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reportuser -d reportdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: report-generator
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://reportuser:reportpass@postgres:5432/reportdb
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - USE_LOCAL_STORAGE=true
      - LOCAL_STORAGE_PATH=/app/storage
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  qdrant_data: